### ISSUE TITLE
Mines placed on ore crash game

### ISSUE THREAD

**Issue by oobee85** [oobee85/civilicraftfortressII#3]
Exception in thread "Thread-2" java.lang.NullPointerException
	at world.Resource.<init>(Resource.java:15)
	at world.Tile.setResource(Tile.java:63)
	at ui.Game.updateBuildingAction(Game.java:214)
	at ui.Game.gameTick(Game.java:175)
	at ui.Frame.lambda$15(Frame.java:872)
	at java.lang.Thread.run(Unknown Source)

**Comment by 0leks** [comment]
fixed: 5e6486f415dc7270b296c51c5bd211f45565a69f
